max_configs:
    1000

hyperparameters:
    seed: [42]
    save: [False]
    tr: [False]
    device: ['cuda:3']
    task: ['smnist']
    block: ['ESN']
    layers: [1]
    dmodel: [32] # 2 * 1024
    rbatch: [1024]
    last: [False]
    readout: ['ridge']
    inputscaling: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
    biasscaling: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
    rho: [0.9, 0.95, 1.0, 1.05, 1.1]
    leaky: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
    transient: [ -1 ]
    regul: [ 0.8 ]
