max_configs:
    800

hyperparameters:
    seed: [42]
    save: [False]
    tr: [False]
    # DEVICE
    device: ["cuda:3"]
    # TASK
    task: ["smnist"]
    # ARCHITECTURE
    block: ["S4"]
    layers: [2]
    dmodel: [256]
    encoder: ["conv1d"]
    decoder: ["conv1d"]
    layerdrop: [0.0]
    # BLOCK
    dropout: [0.1]
    tiedropout: [True]
    dstate: [64]
    kernellr: [0.001]
    low: [0.001]
    high: [0.1]
    init: ["legs"]
    bidirectional: [True]
    finalact: ["glu"]
    nssm: [1]
    # LEARNING
    batch: [128]
    lr: [0.01]
    wd: [0.05]
    plateau: [0.2]
    epochs: [200]
    patience: [10]
