max_configs:
    800

hyperparameters:
    seed: [42]
    save: [False]
    tr: [False]
    # DEVICE
    device: ["cuda:3"]
    # TASK
    task: ["smnist"]
    # ARCHITECTURE
    block: ["LRSSM"]
    layers: [8]
    dmodel: [64]
    encoder: ["conv1d"]
    decoder: ["conv1d"]
    layerdrop: [0.0]
    # BLOCK
    dstate: [64]
    dropout: [0.0]
    kernel: ["Vr"]
    minscaleencoder: [0.0]
    maxscaleencoder: [1.0]
    discrete: [False]
    strong: [-4.0]
    weak: [-0.025]
    low: [0.001]
    high: [0.1]
    minscaleB: [0.0]
    maxscaleB: [0.25]
    minscaleC: [0.0]
    maxscaleC: [1.0]
    minscaleD: [1.0]
    maxscaleD: [1.0]
    mlplayers: [1]
    act: ["glu"]
    # LEARNING
    batch: [64]
    lr: [0.01]
    wd: [0.05]
    plateau: [0.2]
    epochs: [200]
    patience: [10]
